### ISSUE TITLE
Tests fail because of GoRouter error

### ISSUE THREAD

**Issue by arnaugomez** [mrmilu/flutter_base#31]
## Environment

**Package version:**  main
**Platform:** test, VS Code
**Device information:**  MacBook Pro

## Description

**Expected behavior:**
All tests pass

**Current behavior:**
Not all tests pass. The following tests fail because of GoRouter error:
- When user go to confirm page from deeplink can continue to change password page
- When user enter invalid email show snackbar error
- When user enter valid data and tap button complete action

## Steps to reproduce

Run all tests

## Images   
<img width="1184" alt="image" src="https://github.com/mrmilu/flutter_base/assets/66358043/93714e38-6b10-49ce-94ed-bc70154fd17b">

## Stacktrace/Logcat   
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building Builder(dirty):
type 'Null' is not a subtype of type 'ChangePasswordPageData' in type cast

The relevant error-causing widget was:
  Builder
  Builder:file:///Users/arnau/.pub-cache/hosted/pub.dev/go_router-9.0.3/lib/src/builder.dart:102:7

When the exception was thrown, this was the stack:
#0      router.<anonymous closure> (package:flutter_base/ui/router/app_router.dart:67:46)
#1      RouteBuilder._buildPageForGoRoute (package:go_router/src/builder.dart:363:45)
#2      RouteBuilder._buildRecursive (package:go_router/src/builder.dart:223:13)
#3      RouteBuilder._buildPages (package:go_router/src/builder.dart:162:7)
#4      RouteBuilder.tryBuild (package:go_router/src/builder.dart:135:9)
#5      RouteBuilder.build.<anonymous closure> (package:go_router/src/builder.dart:106:33)
#6      Builder.build (package:flutter/src/widgets/basic.dart:7448:48)
#7      StatelessElement.build (package:flutter/src/widgets/framework.dart:5038:49)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950:5)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944:5)
...     Normal element mounting (151 frames)
#162    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953:16)
#163    Element.updateChild (package:flutter/src/widgets/framework.dart:3676:20)
#164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#165    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#167    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#168    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1336:19)
#169    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#170    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#171    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#172    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1185:9)
#175    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#176    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1171:27)
#177    WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:679:23)
#180    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#181    WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:672:27)
#182    PumpApp.pumpAppRoute (file:///Users/arnau/Desktop/work/flutter_base/test/helpers/pump_app.dart:57:11)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by arnaugomez** [comment]
It appears that the page widget does not receive the necessary args when it is rendered by GoRouter. The args are null.

**Comment by arnaugomez** [comment]
It appears that the page widget does not receive the necessary args when it is rendered by GoRouter. The args are null.
